### PR TITLE
TBF-001: Added externalflag to link

### LINKED ISSUE #26: TBF-001
Screenshot_2021-09-30 The Baseball Field Friends - Streaming music

The link to old tbs site is broken - probably because of a '/' before it (/https://thebaseballfield.se/old/).

Your mission, should you chose to accept it, is to make the link work. The link component in question is located at :47 in StartPage.js. The other, similar, links on that page has already been fixed.

### PR DESCRIPTION
**Pull request by KarolinaBladh**

### CODE REVIEW

File: src/components/pages/StartPage.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ const StartPage = () => {
                             Sj&ouml;buse Records</b>, now brings you that good old music in a modern way.</p>
                         <h2>Extra content</h2>
                         <h3>Links</h3>
-                        <p><IconLink link={"https://thebaseballfield.se/old/"} text={"The old TBF/VVM site"} icon={"sitemap"}/></p>
+                        <p><IconLink link={"https://thebaseballfield.se/old/"} text={"The old TBF/VVM site"} icon={"sitemap"} external={true}/></p>
```
Comment (JoakimJohnsson) [inline src/components/pages/StartPage.js:47]: Looks good!

**Review by JoakimJohnsson — APPROVED** [review]
